# Generated by Django 3.1.13 on 2021-09-13 20:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkin',
            old_name='nhospedes',
            new_name='numero_de_hospedes',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='id',
        ),
        migrations.AlterField(
            model_name='checkin',
            name='cod_reserva',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
