# Generated by Django 3.1.13 on 2021-09-13 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210913_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkin',
            old_name='npets',
            new_name='número_de_hospedes',
        ),
        migrations.RenameField(
            model_name='checkin',
            old_name='numero_de_hospedes',
            new_name='número_de_pets',
        ),
    ]
