# Generated by Django 3.1.13 on 2021-09-13 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210913_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkin',
            old_name='cod_reserva',
            new_name='codigo_reserva',
        ),
        migrations.RenameField(
            model_name='checkin',
            old_name='user',
            new_name='hospede',
        ),
    ]
