# Generated by Django 3.1.13 on 2021-09-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210913_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='informações',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
