# Generated by Django 3.1.13 on 2021-09-15 23:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210914_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='imovel',
            fields=[
                ('hospede', models.CharField(max_length=255)),
                ('número_de_hospedes', models.IntegerField()),
                ('número_de_pets', models.IntegerField()),
                ('criado', models.DateField(auto_now_add=True)),
                ('dia_da_entrada', models.DateField()),
                ('hora_da_entrada', models.TimeField()),
                ('dia_da_saida', models.DateField()),
                ('hora_da_saida', models.TimeField()),
                ('diarias_reservadas', models.IntegerField()),
                ('preço', models.FloatField()),
                ('endereço', models.CharField(max_length=255)),
                ('codigo_reserva', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telefone', models.IntegerField()),
                ('informações', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='checkin',
        ),
        migrations.RemoveField(
            model_name='limpeza',
            name='checkout',
        ),
        migrations.DeleteModel(
            name='checkin',
        ),
        migrations.DeleteModel(
            name='checkout',
        ),
    ]
