# Generated by Django 3.1.13 on 2021-09-15 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210915_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='telefone',
            field=models.BigIntegerField(max_length=11),
        ),
    ]
