# Generated by Django 3.1.13 on 2021-09-17 01:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20210916_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='imovel',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.imovel'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkin_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 22, 49, 47, 557378)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkout_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 17, 22, 49, 47, 557418)),
        ),
    ]
