# Generated by Django 3.1.13 on 2021-09-17 01:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20210916_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='hospede',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='imovel',
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkin_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 22, 52, 41, 693631)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkout_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 17, 22, 52, 41, 693679)),
        ),
    ]
