# Generated by Django 3.1.13 on 2021-09-17 02:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20210916_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='hospede',
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkin_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 23, 0, 41, 413882)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkout_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 17, 23, 0, 41, 413930)),
        ),
    ]
