# Generated by Django 3.1.13 on 2021-09-17 02:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20210916_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='diarias',
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkin_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 23, 49, 52, 349521)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkout_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 23, 49, 52, 349559)),
        ),
    ]
